name = "_empty"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2025-03-05"
rules = [{ type = "ESModule", globs = ["**/*.js"] }]
compatibility_flags = ["nodejs_compat_v2"]
assets = { directory = "./.output/public/", binding = "ASSETS" }

[[r2_buckets]]
binding = "R2Storage"
bucket_name = "longtake-v2"
remote = true